In [47]:
#Rishabh Kumar 
#20112092

In [48]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.svm import SVC

In [49]:
rawdata = pd.read_csv("advertising.csv")
rawdata.shape

(1000, 10)

In [50]:
rawdata.head(10)

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                     68.95   35     61833.90                256.09   
1                     80.23   31     68441.85                193.77   
2                     69.47   26     59785.94                236.50   
3                     74.15   29     54806.18                245.89   
4                     68.37   35     73889.99                225.58   
5                     59.99   23     59761.56                226.74   
6                     88.91   33     53852.85                208.36   
7                     66.00   48     24593.33                131.76   
8                     74.53   30     68862.00                221.51   
9                     69.88   20     55642.32                183.82   

                           Ad Topic Line              City  Male     Country  \
0     Cloned 5thgeneration orchestration       Wrightburgh     0     Tunisia   
1     Monitored national standardization         West Jodi     1       Nauru   
2       Organic bottom-line service-desk          Davidton     0  San Marino   
3  Triple-buffered reciprocal time-frame    West Terrifurt     1       Italy   
4          Robust logistical utilization      South Manuel     0     Iceland   
5        Sharable client-driven software         Jamieberg     1      Norway   
6             Enhanced dedicated support       Brandonstad     0     Myanmar   
7               Reactive local challenge  Port Jefferybury     1   Australia   
8         Configurable coherent function        West Colin     1     Grenada   
9     Mandatory homogeneous architecture        Ramirezton     1       Ghana   

          Timestamp  Clicked on Ad  
0  27-03-2016 00:53              0  
1  04-04-2016 01:39              0  
2  13-03-2016 20:35              0  
3  10-01-2016 02:31              0  
4  03-06-2016 03:36              0  
5  19-05-2016 14:30              0  
6  28-01-2016 20:59              0  
7  07-03-2016 01:40              1  
8  18-04-2016 09:33              0  
9  11-07-2016 01:42              0

In [37]:
rawdata.shape

(1000, 10)

In [38]:
del_columns = ["Ad Topic Line","City","Country","Timestamp"]
rawdata.drop(columns = del_columns, inplace = True)

In [39]:
rawdata.head(10)

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male  \
0                     68.95   35     61833.90                256.09     0   
1                     80.23   31     68441.85                193.77     1   
2                     69.47   26     59785.94                236.50     0   
3                     74.15   29     54806.18                245.89     1   
4                     68.37   35     73889.99                225.58     0   
5                     59.99   23     59761.56                226.74     1   
6                     88.91   33     53852.85                208.36     0   
7                     66.00   48     24593.33                131.76     1   
8                     74.53   30     68862.00                221.51     1   
9                     69.88   20     55642.32                183.82     1   

   Clicked on Ad  
0              0  
1              0  
2              0  
3              0  
4              0  
5              0  
6              0  
7              1  
8              0  
9              0

In [40]:
x = rawdata.drop(columns = "Clicked on Ad")
x.head(10)

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male
0                     68.95   35     61833.90                256.09     0
1                     80.23   31     68441.85                193.77     1
2                     69.47   26     59785.94                236.50     0
3                     74.15   29     54806.18                245.89     1
4                     68.37   35     73889.99                225.58     0
5                     59.99   23     59761.56                226.74     1
6                     88.91   33     53852.85                208.36     0
7                     66.00   48     24593.33                131.76     1
8                     74.53   30     68862.00                221.51     1
9                     69.88   20     55642.32                183.82     1

In [41]:
y = rawdata["Clicked on Ad"].copy()
y.head(10)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    1
8    0
9    0
Name: Clicked on Ad, dtype: int64

In [275]:
# model = LogisticRegression()
model = SVC(kernel = 'linear' , C = 100)
#model = SVC(kernel = 'poly',degree = 2)
#model = SVC(kernel = 'poly', degree = 2, C = 100000)
# model = SVC()

In [276]:
# ?SVC

In [277]:
model.fit(x,y)

SVC(C=100, kernel='linear')

In [278]:
pred = model.predict(x)

In [279]:
confusion_matrix(pred,y)

array([[490,  19],
       [ 10, 481]], dtype=int64)

In [280]:
SupportVector = model.support_vectors_

In [281]:
# ?model


In [282]:
SupportVector.size

355

In [283]:
accuracy = model.score(x, y)
accuracy

0.971

In [263]:
# C = 0.01 number of support vectors 365 accuracy 0.97
# C = 0.1 number of support vectors 345 accuracy 0.972
# C = 1 number of support vectors 340 accuracy 0.968
# C = 10 number of support vectors 340 accuracy 0.969
# C = 100 number of support vectors 355 accuracy 0.971
# C = 1000 number of support vectors 360 accuracy 0.972

In [231]:
model = SVC(kernel = 'poly',degree = 2, C = 0.01)

In [232]:
model.fit(x,y)

SVC(C=0.01, degree=2, kernel='poly')

In [233]:
pred2 = model.predict(x)

In [234]:
confusion_matrix(pred2,y)

array([[388, 173],
       [112, 327]], dtype=int64)

In [193]:
SupportVector2 = model.support_vectors_

In [194]:
SupportVector2.size

4360

In [195]:
accuracy = model.score(x, y)
accuracy

0.715

In [198]:
# C = 0.01 number of support vectors 4360 accuracy 0.715
# C = 0.1 number of support vectors 3540 accuracy 0.711
# C = 1 number of support vectors 3380 accuracy 0.708
# C = 10 number of support vectors 3360 accuracy 0.969
# C = 100 number of support vectors 3355 accuracy 0.747
# C = 1000 number of support vectors 2890 accuracy 0.913

In [325]:
model = SVC(kernel = 'rbf' , C = 1000)

In [326]:
# ?model

In [327]:
model.fit(x,y)


SVC(C=1000)

In [328]:
pred3 = model.predict(x)

In [329]:
confusion_matrix(pred3,y)

array([[465,  95],
       [ 35, 405]], dtype=int64)

In [330]:
SupportVector3 = model.support_vectors_

In [331]:
SupportVector3.size

2940

In [332]:
accuracy = model.score(x, y)
accuracy

0.87

In [333]:
# C = 0.01 number of support vectors 5000 accuracy 0.703
# C = 0.1 number of support vectors 3700 accuracy 0.713
# C = 1 number of support vectors 3290 accuracy 0.715
# C = 10 number of support vectors 3180 accuracy 0.717
# C = 100 number of support vectors 3150 accuracy 0.736
# C = 1000 number of support vectors 2940 accuracy 0.87